#!/usr/bin/env python3
"""Build the minimal raw-data archive described by raw_data_archive_manifest.

This script is intentionally local-only: it creates a timestamped staging
directory and deterministic ``.tar.gz`` archive under ``tmp/``.  It does not
upload data, delete data, or modify the manuscript.  The generated report is a
handoff artifact for a future Zenodo/OSF/journal supplement upload.
"""

from __future__ import annotations

import argparse
import datetime as _dt
import gzip
import hashlib
import json
import shutil
import subprocess
import tarfile
from dataclasses import asdict, dataclass
from pathlib import Path


REVISION_REL = Path("Paper/revision_2026-06-19")
MANIFEST_REL = REVISION_REL / "raw_data_archive_manifest.json"
REPORT_JSON_REL = REVISION_REL / "raw_data_archive_build_report.json"
REPORT_MD_REL = REVISION_REL / "raw_data_archive_build_report.md"
DEFAULT_RUNS_REL = Path("tmp/raw_data_archive/runs")
ARCHIVE_ROOT = "NLS_numerical_study_raw_data_minimal"
CONTENTS_SHA_REL = Path("RAW_DATA_CONTENTS.sha256")


@dataclass
class ArchivedRawFile:
    archive_path: str
    local_path: str
    size_bytes: int
    sha256: str
    source_artifacts: list[str]


def repo_root() -> Path:
    return Path(__file__).resolve().parents[3]


def run_git(root: Path, args: list[str]) -> str:
    proc = subprocess.run(["git", *args], cwd=root, text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=True)
    return proc.stdout.strip()


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def copy_raw_file(root: Path, staging_root: Path, rec: dict) -> ArchivedRawFile | None:
    if not rec.get("exists"):
        return None
    src = root / rec["local_path"]
    if not src.is_file():
        return None
    actual_sha = sha256_file(src)
    if rec.get("sha256") and actual_sha != rec["sha256"]:
        raise ValueError(f"SHA-256 mismatch for {rec['local_path']}: manifest={rec['sha256']} actual={actual_sha}")
    dst = staging_root / rec["archive_path"]
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dst)
    return ArchivedRawFile(
        archive_path=rec["archive_path"],
        local_path=rec["local_path"],
        size_bytes=dst.stat().st_size,
        sha256=actual_sha,
        source_artifacts=list(rec.get("source_artifacts", [])),
    )


def write_contents_checksum(staging_root: Path, files: list[ArchivedRawFile]) -> ArchivedRawFile:
    contents = staging_root / CONTENTS_SHA_REL
    lines = [f"{rec.sha256}  {rec.archive_path}" for rec in sorted(files, key=lambda item: item.archive_path)]
    contents.write_text("\n".join(lines) + "\n")
    return ArchivedRawFile(
        archive_path=str(CONTENTS_SHA_REL),
        local_path="generated checksum index",
        size_bytes=contents.stat().st_size,
        sha256=sha256_file(contents),
        source_artifacts=["generated by build_raw_data_archive.py"],
    )


def deterministic_tar_gz(staging_root: Path, archive_path: Path) -> None:
    archive_path.parent.mkdir(parents=True, exist_ok=True)
    with archive_path.open("wb") as raw:
        with gzip.GzipFile(filename="", mode="wb", fileobj=raw, mtime=0) as gz:
            with tarfile.open(fileobj=gz, mode="w") as tar:
                for path in sorted(staging_root.rglob("*")):
                    rel = path.relative_to(staging_root)
                    info = tar.gettarinfo(str(path), arcname=str(Path(ARCHIVE_ROOT) / rel))
                    info.uid = 0
                    info.gid = 0
                    info.uname = ""
                    info.gname = ""
                    info.mtime = 0
                    if path.is_file():
                        with path.open("rb") as f:
                            tar.addfile(info, f)
                    else:
                        tar.addfile(info)


def write_markdown(path: Path, payload: dict) -> None:
    summary = payload["summary"]
    archive = payload["archive"]
    lines = [
        "# Raw-data archive build report",
        "",
        f"Generated: `{payload['generated_at_utc']}`",
        "",
        f"Status: **{payload['status']}**",
        "",
        "## Archive",
        "",
        f"- Archive path: `{archive['path']}`",
        f"- Archive bytes: {archive['size_bytes']}",
        f"- Archive SHA-256: `{archive['sha256']}`",
        f"- Staging directory: `{payload['staging_directory']}`",
        "",
        "## Summary",
        "",
        "| Metric | Count |",
        "|---|---:|",
        f"| Manifest raw-file records | {summary['manifest_raw_file_records']} |",
        f"| Archived raw files | {summary['archived_raw_file_count']} |",
        f"| Archived raw-data bytes | {summary['archived_raw_file_bytes']} |",
        f"| Missing raw files | {summary['missing_raw_file_count']} |",
        f"| Checksum index files | {summary['checksum_index_file_count']} |",
        "",
        "## Notes",
        "",
        "- The archive preserves the `raw_data/...` paths listed in `raw_data_archive_manifest.md`.",
        "- The archive is written under `tmp/` and is not intended to be committed to Git.",
        "- The file `RAW_DATA_CONTENTS.sha256` inside the archive records SHA-256 checksums for each archived raw file.",
        "- Upload the `.tar.gz` to Zenodo/OSF/journal storage only after the authors choose the raw-data release route.",
        "",
        "## Missing files",
        "",
    ]
    if payload["missing_raw_files"]:
        for rel in payload["missing_raw_files"]:
            lines.append(f"- `{rel}`")
    else:
        lines.append("- None.")
    path.write_text("\n".join(lines) + "\n")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output-runs-dir", default=str(DEFAULT_RUNS_REL), help="Directory under the repo root for timestamped raw-data archive runs.")
    args = parser.parse_args()

    root = repo_root()
    revision = root / REVISION_REL
    manifest_path = root / MANIFEST_REL
    manifest = json.loads(manifest_path.read_text())

    now = _dt.datetime.now(_dt.timezone.utc)
    run_id = now.strftime("%Y%m%dT%H%M%SZ")
    run_dir = root / args.output_runs_dir / run_id
    staging_root = run_dir / ARCHIVE_ROOT
    archive_path = run_dir / f"{ARCHIVE_ROOT}.tar.gz"
    staging_root.mkdir(parents=True, exist_ok=False)

    archived: list[ArchivedRawFile] = []
    missing: list[str] = []
    for rec in manifest["raw_files"]:
        copied = copy_raw_file(root, staging_root, rec)
        if copied is None:
            missing.append(rec["local_path"])
            continue
        archived.append(copied)

    checksum_record = write_contents_checksum(staging_root, archived)
    deterministic_tar_gz(staging_root, archive_path)
    archive_sha = sha256_file(archive_path)

    status = "PASS" if not missing else "FAIL"
    payload = {
        "generated_at_utc": now.isoformat(),
        "script": str((revision / "scripts/build_raw_data_archive.py").relative_to(root)),
        "source_manifest": str(manifest_path.relative_to(root)),
        "git_branch": run_git(root, ["branch", "--show-current"]),
        "git_head": run_git(root, ["rev-parse", "HEAD"]),
        "staging_directory": str(staging_root.relative_to(root)),
        "archive": {
            "path": str(archive_path.relative_to(root)),
            "size_bytes": archive_path.stat().st_size,
            "sha256": archive_sha,
        },
        "status": status,
        "summary": {
            "manifest_raw_file_records": len(manifest["raw_files"]),
            "archived_raw_file_count": len(archived),
            "archived_raw_file_bytes": sum(rec.size_bytes for rec in archived),
            "missing_raw_file_count": len(missing),
            "checksum_index_file_count": 1,
        },
        "missing_raw_files": missing,
        "archived_raw_files": [asdict(rec) for rec in archived],
        "checksum_index": asdict(checksum_record),
    }

    json_path = root / REPORT_JSON_REL
    md_path = root / REPORT_MD_REL
    json_path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n")
    write_markdown(md_path, payload)
    print(json.dumps({"status": status, "archive": payload["archive"], "summary": payload["summary"]}, indent=2))
    return 0 if status == "PASS" else 1


if __name__ == "__main__":
    raise SystemExit(main())
